variable "access_key_id" {}
variable "secret_key_id" {}
variable "region" {}
variable "image_id" {}
variable "control_plane_vm_type" {}
variable "control_plane_count" {}
variable "control_plane_volume_type" {}
variable "control_plane_volume_size" {}
variable "control_plane_iops" {}
variable "worker_vm_type" {}
variable "worker_count" {}
variable "worker_volume_type" {}
variable "worker_volume_size" {}
variable "worker_iops" {}
variable "bastion_vm_type" {}
variable "bastion_volume_type" {}
variable "bastion_volume_size" {}
variable "bastion_iops" {}
variable "cluster_name" {}
variable "kubernetes_version" {}
variable "will_install_ccm" {}
