apiVersion: v1
kind: Namespace
metadata:
  name: "dynamic-p"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsu-claim
  namespace: dynamic-p
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bsu-sc
  resources:
    requests:
      storage: 4Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: bsu-sc
  namespace: dynamic-p
provisioner: bsu.csi.outscale.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: dynamic-p
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: bsu-claim
