name: 'Destroy cluter'
description: 'Destroy k8s cluster'
inputs:
  osc_access_key:
    description: 'ACCESS KEY'
    required: true
  osc_secret_key:
    description: 'SECRET KEY'
    required: true
  osc_region:
    description: 'Region'
    required: true
  repository_folder:
    description: 'Folder where the repo can be found'
    required: true
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Shutdown the cluster  
      run: ./rke_linux-amd64 remove --config rke/cluster.yml --force
      working-directory: ${{ inputs.repository_folder }}
      shell: bash
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      if: ${{ always() }}
      env:   
        TF_VAR_access_key_id: ${{ inputs.osc_access_key }}
        TF_VAR_secret_key_id: ${{ inputs.osc_secret_key }}
        TF_VAR_region: ${{ inputs.osc_region }}
      working-directory: ${{ inputs.repository_folder }}
      shell: bash
